Update: Editor history visualization
loro-dev/loro-prosemirror pull request #24
Opened 2024-12-23 08:56 UTC by Henry-Wow

Enhanced the editor history visualization system to improve operation history tracking and display in collaborative editing scenarios. The main improvements focus on:

1.  Added `editor-history.ts`:
- Implemented core logic for converting editor operations to DAG nodes

2. Updated history visualization components:
- `BasicWithHistory`: Added single editor history tracking
- `SyncWithHistory`: Improved two-editor synchronization with history
- `OfflineSyncWithHistory`: Enhanced offline/online state handling
- `MultiOfflineSyncWithHistory`: Added support for multiple editor synchronization

2024-12-24 15:46 UTC, Henry-Wow commented
https://github.com/user-attachments/assets/5ff1eb58-7bde-4862-b4c6-c97c37291816

2024-12-24 15:53 UTC, zxch3n commented
Awesome!

2024-12-24 16:16 UTC, zxch3n requested changes

2024-12-24 16:16 UTC, zxch3n commented on examples/stories/src/stories/editor-history.ts
> +const storedOperations: StoredOperation[] = [];
This should be inside `convertSyncStepsToNodes`

2024-12-24 16:16 UTC, zxch3n commented on examples/stories/src/stories/editor-history.ts
> +            if (!storedOperations.some(op => op.id === opId)) {
This is slow, you can use a Set to detect whether it's stored

2025-01-03 12:48 UTC, zxch3n approved these changes

2025-01-03 12:50 UTC, merged